pp = ("Refilwe", "Kgwadi", 16, 5.9, 90, "Mathematics")
pd = ("Mahikeng","Province: Northwest")
pf = ("Current stay: Johannesburg")
print("HEY!!,I am")
personal_details_list = list(pp)
personal_details_list = list(pd)
personal_details_list = list(pf)
print(pp)
print("I'm from...")
print(pd)
print(pf)
print("And I am a student at Codingal")